/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AttendanceCreateNestedManyWithoutCoursesInput } from "./AttendanceCreateNestedManyWithoutCoursesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { GradeCreateNestedManyWithoutCoursesInput } from "./GradeCreateNestedManyWithoutCoursesInput";
import { ScheduleCreateNestedManyWithoutCoursesInput } from "./ScheduleCreateNestedManyWithoutCoursesInput";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";

@InputType()
class CourseCreateInput {
  @ApiProperty({
    required: false,
    type: () => AttendanceCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => AttendanceCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => AttendanceCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  attendances?: AttendanceCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => GradeCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => GradeCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => GradeCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  grades?: GradeCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ScheduleCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ScheduleCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ScheduleCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  schedules?: ScheduleCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolWhereUniqueInput, {
    nullable: true,
  })
  school?: SchoolWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  teacherId?: string | null;
}

export { CourseCreateInput as CourseCreateInput };
